name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Adjust to your Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the project
      - name: Build the binary
        run: go build -o reverse_proxy .

      # Run tests
      - name: Run tests
        run: go test -v ./...
